version: '3.2'

services:
  spark:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_PUBLIC_DNS=localhost      
    ports:
      - '8080:8080'
      - '7077:7077'
      - '4040:4040'

    volumes:
      - ${OUTPUT_PATH_SOURCE}:${OUTPUT_PATH_DEST}
      - ${INPUT_DATA_SOURCE}:${INPUT_DATA_DEST}:ro
      - ${SPARK_ARTIFACT_SOURCE}:${SPARK_ARTIFACT_DEST}
 
  spark-worker-1:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_WORKER_PORT=8881
      - SPARK_WORKER_WEBUI_PORT=8081      
    ports:
      - '8081:8081'
    volumes:
      - ${OUTPUT_PATH_SOURCE}:${OUTPUT_PATH_DEST}
      - ${INPUT_DATA_SOURCE}:${INPUT_DATA_DEST}:ro
      - ${SPARK_ARTIFACT_SOURCE}:${SPARK_ARTIFACT_DEST}      

  spark-worker-2:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_WORKER_PORT=8881
      - SPARK_WORKER_WEBUI_PORT=8081            

    ports:
      - '8082:8082'
    volumes:
      - ${OUTPUT_PATH_SOURCE}:${OUTPUT_PATH_DEST}
      - ${INPUT_DATA_SOURCE}:${INPUT_DATA_DEST}:ro
      - ${SPARK_ARTIFACT_SOURCE}:${SPARK_ARTIFACT_DEST}      